---
name: Config-Format-Ini
version: 0.03
author:
  - 'Ioannis Tambouras <ioannis@cpan.org>'
abstract: Reads INI configuration files
license: perl
requires:
  Attribute::Handlers: 0
  File::Slurp: 0
  Parse::RecDescent: 0
  perl: 5.6
recommends:
  Test::Exception: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 1.0
provides:
  Config::Format::Ini:
    file: lib/Config/Format/Ini.pm
    version: 0.03
  Config::Format::Ini::Grammar:
    file: lib/Config/Format/Ini/Grammar.pm
generated_by: Module::Build version 0.2611
